pipeline{

    agent none  

    stages{
        stage("Build") {
          agent{
              docker{
                  image 'python:2.7.16-slim'
                  args '--user root -v $HOME/.m2:/root/.m2'
              }
          }
            
          when{
            changeset "**/vote/**"
          }
            steps{
                echo "Building a project"
                dir('vote'){
                    sh "pip install -r requirements.txt"
                }
            }
        }
        stage("Test") {
          agent{
              docker{
                  image 'python:2.7.16-slim'
                  args '--user root -v $HOME/.m2:/root/.m2'
              }
          }
          when{
            changeset "**/vote/**"
          }
            steps{
                echo "Testing the project"
                dir('vote'){
                    sh "pip install -r requirements.txt'
                    sh "nosetests -v"
                }
            }
        }
        stage("docker-Package") {
            agent any
            when{
                changeset "**/vote/**"
            }
            steps{
                echo "Packaging the product using docker"
                script{
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin'){
                        def workerImg = docker.build("itachi0139/votebuild:v${BUILD_ID}","./vote")
                        workerImg.push()
                        workerImg.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }

    post{
        always{
            echo "Pipeline execution is complete...."
        }
    }

}
