pipeline{

    agent{
        docker{
            image 'python:2.7.16-slim'
            args '-v $HOME/.m2:/root/.m2'
        }
    }   

    stages{
        stage("Build") {
          when{
            changeset "**/vote/**"
          }
            steps{
                echo "Building a project"
                dir('vote'){
                    sh "pip install -r requirements.txt"
                }
            }
        }
        stage("Test") {
          when{
            changeset "**/vote/**"
          }
            steps{
                echo "Testing the project"
                dir('vote'){
                    sh "nosetests -v"
                }
            }
        }
    }

    post{
        always{
            echo "Pipeline execution is complete...."
        }
    }

}
