pipeline{

    agent none

    stages{
        stage("Build") {
            agent{
                docker{
                    image 'maven:3.6.1-jdk-8-alpine'
                    args '-v $HOME/.m2:/root/m2'
                }
            }
            when{
                changeset "**/worker/**"
            }
            steps{
                echo "Building a project"
                dir('worker'){
                    sh "mvn compile"
                }
            }
        }
        stage("Test") {
            agent{
                docker{
                    image 'maven:3.6.1-jdk-8-alpine'
                    args '-v $HOME/.m2:/root/m2'
                }
            }
            when{
                changeset "**/worker/**"
            }
            steps{
                echo "Testing the project"
                dir('worker'){
                    sh "mvn test"
                }
            }
        }
        stage("docker-Package") {
            agent any
            when{
                changeset "**/worker/**"
            }
            steps{
                echo "Packaging the product using docker"
                script{
                    docker.withRegistry('https://index.docker.io/v1', 'dockerlogin'){
                        def workerImg = docker.build("itachi0139/workerbuild:v${BUILD_ID}","./worker")
                        workerImg.push()
                        workerImg.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }

    post{
        always{
            echo "Pipeline execution is complete...."
        }
    }

}
